### ISSUE TITLE
Potential pattern match error in EventAPI

### ISSUE THREAD

**Issue by lancejjohnson** [anthonylebrun/triangle_farms#1]
https://github.com/anthonylebrun/triangle_farms/blob/cb504e81ffeb769edf3873d4f78fa403a5970630/lib/triangle_farms/calendar/event_api.ex#L5

**Comment by anthonylebrun** [comment]
True, but I'm actually ok with it failing completely (it's using valid credentials that I expect to work) and throwing an exception if that happens - I'd want to know and because of the cache, the site probably wouldn't experience downtime @lancejjohnson
